### ISSUE TITLE
Error in config.py with signal_start_index and signal_end_index

### ISSUE THREAD

**Issue by alloyd42486** [adjtomo/pyflex#13]
Hi,
Playing around with pyflex I noticed there may be an error in config.py on lines 250 and 251. It reads,
        self.signal_start_index = **noise_start_index**
        self.signal_end_index = **noise_end_index**
Thus, the signal region is set to be the same as the noise region.
This should instead be,
        self.signal_start_index = **signal_start_index**
        self.signal_end_index = **signal_end_index**

Perhaps there is a newer version I am not seeing and this issue has already been fixed.

Best regards,
Andrew

**Comment by bch0w** [comment]
Thanks for bringing this up. This issue was just fixed in PR https://github.com/adjtomo/pyflex/pull/15
