### ISSUE TITLE
pyflex hangs up till the walltime exceeds

### ISSUE THREAD

**Issue by wjlei1990** [adjtomo/pyflex#5]
Hi Lion,

I got pyflex hangs up when processing a specific trace in asdf data.

This kind of situations happened several times and I am not sure what happened.

I will look into this issue and post updates here.

**Comment by wjlei1990** [comment]
There might be something related to pyasdf.

When I use command:

mpiexec -n 2 python parallel_pyflex.py 

It works.

The number of processor can go from 2 to 8, but 16 processor(mpi) doesn't work

**Comment by krischer** [comment]
Hi Wenjie,

I am pretty sure the problem is not with pyflex but with pyasdf. Can you open an issue in the pyasdf repository with a a short code snippet that illustrates the problem?

Thanks!
